#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>//精确与不精确的内核

#include <CGAL/Point_set_3.h>
#include <CGAL/Point_set_3/IO.h>

#include <CGAL/remove_outliers.h>
#include <CGAL/grid_simplify_point_set.h>
#include <CGAL/jet_smooth_point_set.h>
#include <CGAL/jet_estimate_normals.h>
#include <CGAL/mst_orient_normals.h>

#include <CGAL/poisson_surface_reconstruction.h>
#include <CGAL/Advancing_front_surface_reconstruction.h>
#include <CGAL/Scale_space_surface_reconstruction_3.h>
#include <CGAL/Scale_space_reconstruction_3/Jet_smoother.h>
#include <CGAL/Scale_space_reconstruction_3/Advancing_front_mesher.h>

#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>

#include <cstdlib>
#include <vector>
#include <fstream>

// types
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::FT FT;
typedef Kernel::Point_3 Point_3;
typedef Kernel::Vector_3 Vector_3;
typedef Kernel::Sphere_3 Sphere_3;//三维球体，_3  表示三维
typedef CGAL::Point_set_3<Point_3, Vector_3> Point_set;// 点集类型，包含三维点和法线 

int main(int argc, char* argv[])
{
	//std::string fname = argc == 1 ? CGAL::data_file_path("points_3/kitten.xyz") : argv[1];
	//if (argc < 2)
	//{
	//	std::cerr << "Usage: " << argv[0] << " [input.xyz/off/ply/las]" << std::endl;
	//	std::cerr << "Running " << argv[0] << " data/kitten.xyz -1\n";
	//}
	std::string fname = "E:/opengl/HalCG/CGAL/CGALSample/datas/points_3/kitten.xyz";
	std::ifstream stream(fname, std::ios_base::binary);
	if (!stream)
	{
		std::cerr << "Error: cannot read file " << fname << std::endl;
		return EXIT_FAILURE;
	}

	Point_set points;
	stream >> points;

	std::cout << "Read " << points.size() << " point(s)" << std::endl;
	if (points.empty())
		return EXIT_FAILURE;

	//使用 remove_outliers 函数去除点云中的异常值。这里使用 24 个邻域点来评估每个点是否为异常值，并设置阈值为 5%。
	typename Point_set::iterator rout_it = CGAL::remove_outliers<CGAL::Sequential_tag>
		(points, 24, points.parameters().threshold_percent(5.0));
	points.remove(rout_it, points.end());

	std::cout << points.number_of_removed_points()
		<< " point(s) are outliers." << std::endl;

	// 将点集处理算法应用于 CGAL::Point_set_3 对象不会从内存中删除点，而是将它们放入对象的垃圾中：用户可以释放内存
	points.collect_garbage();

	//使用 6 个点的邻域计算平均间距
	double spacing = CGAL::compute_average_spacing<CGAL::Sequential_tag>(points, 6);

	// 使用大小为 2 * 平均间距的网格进行简化
	typename Point_set::iterator gsim_it = CGAL::grid_simplify_point_set(points, 2. * spacing);
	points.remove(gsim_it, points.end());

	std::cout << points.number_of_removed_points()
		<< " point(s) removed after simplification." << std::endl;

	points.collect_garbage();

	//使用 Jet 平滑算法对点集进行平滑处理，提高重建结果的质量。
	CGAL::jet_smooth_point_set<CGAL::Sequential_tag>(points, 24);


	int reconstruction_choice
		= argc == 1 ? -1 : (argc < 3 ? 0 : atoi(argv[2]));

	//使用 Poisson 表面重建方法，从点云中重建出表面。
	if (reconstruction_choice == 0 || reconstruction_choice == -1) // Poisson
	{
		//估计点云中每个点的法线向量。
		//这个模板函数使用“顺序标签”（Sequential_tag），表明算法是针对顺序处理的，将依次处理点云中的每个点。CGAL 也提供了并行处理的选项，如 Parallel_tag。
		//24: 这是一个整数参数，表示在计算法线时使用 24 个邻居（即使用周围 24 个点的局部结构信息）。选择邻居的数量可以影响法线估计的结果，更多的邻居可能会提供更加平滑和一致的法线。
		CGAL::jet_estimate_normals<CGAL::Sequential_tag>
			(points, 24); // Use 24 neighbors

		//估计出的法线进行定向。法线的方向可能不一致，有些法线可能指向内侧或外侧。通过这个步骤，可以确保法线朝向一致，符合一定的标准。
		//返回一个指向第一个未定向法线（即法线方向不一致的点）的迭代器。如果所有法线都已经正确定向，则该迭代器可能指向 points.end()。
		//typename Point_set::iterator 表示返回值的类型，即点集中的迭代器类型，用于遍历点云。
		typename Point_set::iterator unoriented_points_begin =
			CGAL::mst_orient_normals(points, 24); // Use 24 neighbors

		points.remove(unoriented_points_begin, points.end());

		CGAL::Surface_mesh<Point_3> output_mesh;
		CGAL::poisson_surface_reconstruction_delaunay	//使用 Poisson 表面重建方法，从点云中重建出表面。
		(points.begin(), points.end(),
			points.point_map(), points.normal_map(),
			output_mesh, spacing);

		std::ofstream f("out_poisson.ply", std::ios_base::binary);
		CGAL::IO::set_binary_mode(f);
		CGAL::IO::write_PLY(f, output_mesh);
		f.close();
	}

	//使用前进表面算法进行重建，并将生成的三角面片存储到 facets 向量中。
	if (reconstruction_choice == 1 || reconstruction_choice == -1) // Advancing front
	{
		typedef std::array<std::size_t, 3> Facet; // Facet 是一个类型定义，表示一个由三个索引组成的数组（std::array）。这三个索引用于表示一个三角形面（facet）在点云中的三个顶点。

		std::vector<Facet> facets;

		//1. 根据给定的点集进行表面重建，结果存储在 facets 向量中。
		CGAL::advancing_front_surface_reconstruction(points.points().begin(),
			points.points().end(),
			std::back_inserter(facets));//函数适配器用于将生成的三角形面反向插入到 facets 向量中。
		std::cout << facets.size()
			<< " facet(s) generated by reconstruction." << std::endl;

		//2. 将原始点云中的点从 points 复制到 vertices 向量中, 为了方便后续的随机访问.
		std::vector<Point_3> vertices;
		vertices.reserve(points.size());
		std::copy(points.points().begin(), points.points().end(), std::back_inserter(vertices));

		//3. 将点集和生成的面结构整合到一起，形成一个完整的三维网格模型。
		CGAL::Surface_mesh<Point_3> output_mesh;
		CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(vertices, facets, output_mesh);	//将顶点（vertices）和三角形面（facets）转换为完整的表面网格 output_mesh。
		std::ofstream f("out_af.off");
		f << output_mesh;
		f.close();
	}

	//使用尺度空间重建方法，可以进一步平滑点集并生成表面。
	if (reconstruction_choice == 2 || reconstruction_choice == -1) // Scale space
	{
		//尺度空间表面重建算法
		CGAL::Scale_space_surface_reconstruction_3<Kernel> reconstruct
		(points.points().begin(), points.points().end());

		//  使用 Jet 平滑算法对表面进行平滑处理，共进行 4 次迭代。
		reconstruct.increase_scale(4, CGAL::Scale_space_reconstruction_3::Jet_smoother<Kernel>());//通过增加平滑参数的尺度来改善表面的平滑性。
		// 使用“前进前缘”算法生成三角网格，最大三角形边长设置为 0.5。
		reconstruct.reconstruct_surface(CGAL::Scale_space_reconstruction_3::Advancing_front_mesher<Kernel>(0.5));

		std::ofstream f("out_sp.off");
		//创建一个输出文件 out_sp.off，并写入文件头信息。
		f << "OFF" << std::endl << points.size() << " "
			<< reconstruct.number_of_facets() << " 0" << std::endl;
		//遍历点云的每个索引，输出每个点的坐标信息到文件中。
		for (Point_set::Index idx : points)
			f << points.point(idx) << std::endl;
		// 遍历生成的三角形面，并将其索引信息写入文件。
		for (const auto& facet : CGAL::make_range(reconstruct.facets_begin(), reconstruct.facets_end()))
			f << "3 " << facet[0] << " " << facet[1] << " " << facet[2] << std::endl;
		f.close();
	}
	else // Handle error
	{
		std::cerr << "Error: invalid reconstruction id: " << reconstruction_choice << std::endl;
		return EXIT_FAILURE;
	}

	return EXIT_SUCCESS;
}

/*
https://sider.ai/share/ec326167f3ba67240d2d0282a7936bc8
*/

/*
`typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;` 这行代码定义了一个几何内核 `Kernel`，它是 CGAL（Computational Geometry Algorithms Library）库中的一种内核类型。

### 详细解释：

1. **几何内核的概念**:
   - 在计算几何中，**内核**（Kernel）是一个用于定义几何对象（如点、线、平面、曲面等）及其操作（如相交、距离计算等）的基础。不同的内核提供不同的准确性与性能特点。

2. **`Exact_predicates_inexact_constructions_kernel`**:
   - 这个内核类型结合了 **精确** 和 **不精确** 的构造方法:
	 - **Exact predicates**（精确的判别）意味着在进行几何判断（例如点是否在多边形内部、线段是否相交等）时，使用精确的数值算法，确保结果的正确性。这通常是通过使用 **有理数** 或 **大整数** 来实现的。
	 - **Inexact constructions**（不精确的构造）表明在构造几何对象（例如点、线段、三角形等）时可以使用浮点数，提供更快的运行时间，但可能会牺牲一些精度。

3. **适用场景**:
   - 这种内核类型非常适合于现实世界的三维几何应用，既要求高的运算准确性，又不希望在构造对象时过于消耗时间。它是很多 CGAL 算法的默认选择，适合处理复杂的几何计算。
*/

/*
`typedef Kernel::FT FT;` 这一行代码定义了一个类型别名 `FT`，它代表了与之前定义的几何内核 `Kernel` 相关联的数值类型。在 CGAL 中，`Kernel::FT` 通常是一个用于表示数值的类型，但具体的实现会根据所使用的内核而有所不同。

### `Kernel::FT` 的详细说明：

1. **数值类型**:
   - `FT` 是 "Field Type"（域类型）的缩写，表示在几何计算中使用的数值类型。它用于存储数值数据（如浮点数、整数等），而具体类型依据所使用的几何内核而变化。

2. **根据内核的不同**:
   - 在使用 `CGAL::Exact_predicates_inexact_constructions_kernel` 时，`Kernel::FT` 通常表示 `double` 类型，因为这个内核支持浮点数的构造，且使用了精确的判别机制。
   - 对于其他内核，比如 `CGAL::Exact_predicates_exact_constructions_kernel`，`Kernel::FT` 可能代表有理数（`CGAL::Gmpq`）或其他更复杂的数值类型，以提供更高的精度和准确性。

3. **使用场景**:
   - 在 CGAL 中，`FT` 类型被广泛用于表示几何对象的坐标、距离、法线、面积等数值计算。通过使用 `FT` 作为通用类型，可以确保代码的可移植性和灵活性，能够在不同的内核之间进行切换而不需要修改太多代码。
*/